#!/bin/sh
#####################
# HUBBUB - ftp setup

# STEPS #############
# 1) format drive
# 2) fstab drive
# 3) setup anony-only ftpd
# 4) setup ftp user
# 5) setup ftp location

# 1 #################
sysctl hw.disknames; #find drive name
drive=; #set drive name
dmesg | grep $drive; # confirm drive
disklabel $drive;
newfs $drive;

# 2 #################
drive=$drive"c";
echo '/dev/$drive /ftp rw 1 1' >> /etc/fstab;

# 3 #################
echo 'ftpd_flags=-A' >> /etc/rc.conf.local;

# 4 #################
adduser;
# > ftp
# >
# > nologin
# > 3001
# > ftp
# > no
# > default
# > 
# > y
usermod -d /ftp ftp;
rm -r /home/ftp;

# 5 #################
mkdir /ftp;
chown root /ftp;
chmod 555 /ftp;
