#!/usr/local/bin/perl
use strict; use warnings;
#
###########################
# NFS_SETUP - One Time Only

sub
`zfs create zroot/nfs`;
`zfs create zroot/ftp`;

`mkdir /HIVE && chmod 550 /HIVE`;
`mkdir /net && chmod 550 /net`;
`mkdir /pool && chmod 550 /pool/`;
`mkdir /g && chmod 550 /g/`;

`zfs set sharenfs=on zroot/nfs`;
`mkdir /zroot/nfs/pub`;
`mkdir /zroot/nfs/dump`;
`chmod 0777 /zroot/nfs/pub`;
`chmod 0333 /zroot/nfs/dump`;
`chmod 0777 /zroot/ftp/pub`;
`chmod 0333 /zroot/ftp/dump`;
`echo 'console none unknown off insecure' >> /etc/ttys`;
`echo 'crypt_default=blf' >> /etc/auth.conf`;
`sed 'passwd_format="blf"'`;
