#!/usr/local/bin/perl
use strict; use warnings;
use Exporter;
package HB::POP_DIST;
@EXPORT = qw(pop_dist1 pop_dist2);
#
########################################
# GRAB BY                              #

# BSD PORTS ###########################
sub pop_dist1
{
  `cd /usr/ports/security/nmap && make fetch`;
  `cp /usrports/distfiles/nmap* /usb/dist/`;
}
## make fetch from /usr/ports/$pkg_path
## cp /usr/ports/distfiles/$pkg /usb/distfiles 

# PERL MODS ###########################
sub pop_dist2
{
  `cd /usb/dist/`;
  my @mod = ('LWP::UserAgent', 'File::Find::Rule', 'Digest::SHA', \
    'Parallel::ForkManager', 'File::LibMagic', 'List::Utils', \
    'Const::Fast', 'Archive::Any', 'LWP::Protocol::https', \
    '', '');
  for my $mod (@mod)
    { `cpan -g $mod`; }
}
