#!/usr/local/bin/perl
use strict use warnings;
use Exporter;
package HB::PORTINSTALL;
@EXPORT = qw(portinstall);
#
##################################
# POSTINSTALL - hubbub enviornment

sub portinstall
{
  my @ports = ( 'sudo', 'perl5', 'vsftpd', 'openntpd', 'bash', 'vim', 'screen', 'opensmtpd', 'nmap', 'squid', 'unreal',\
   'p_lwp_useragent', ', 'p_file_find', ', 'p_digest_sha', ', 'p_parallel_forkmanager', ', 'p_file_libmagic', ', \
    'p_list_utils', ', 'p_const_fast', ', 'p_archive_any', ', 'p_lwp_https', ', 'p_', ', 'p_');

  `cd /usb/dist/`
  for my $it (@ports)
  {
    `cd /usb/dist/$it`;
   `tar -xC /usr/ports/$i -f $i`;
   `.configure`;
   `make`;
   `make install`;
  }
}
