#!/usr/local/bin/perl
use strict use warnings;
use Exporter;
package HB::PORTINSTALL;
@EXPORT = qw(portinstall);
#
##################################
# POSTINSTALL - hubbub enviornment

sub portinstall
{
#  my @ports = ( 'sudo', 'perl5', 'vsftpd', 'openntpd', 'bash', 'vim', 'screen', 'opensmtpd', 'nmap', 'squid', 'unreal',\
  my @ports = ( 'perl5', 'vsftpd', 'openntpd', 'bash', 'vim', 'opensmtpd', 'nmap', 'squid', \
    'p.lwp_useragent', 'p.file_find', 'p.digest_sha', 'p.parallel_forkmanager', 'p.file_libmagic', \
    'p.list_utils', 'p.const_fast', 'p.archive_any', 'p.lwp_https');

  for my $it (@ports)
  {
    `cd /usb/dist && cp -R $it/usb/dist/$it && tar -xC /usr/ports/$it -f $it`;

    `cd /usr/ports/$it && ./configure && make && make install`;
  }
}
