#!/usr/local/bin/perl
use strict use warnings;
#
##################################
# POSTINSTALL - hubbub enviornment

my @ports = ( 'sudo', 'perl5', 'vsftpd', 'openntpd', 'bash', 'vim', 'screen', 'opensmtpd', 'nmap', 'squid', 'unreal',\
  'p_lwp_useragent', ', 'p_file_find', ', 'p_digest_sha', ', 'p_parallel_forkmanager', ', 'p_file_libmagic', ', \
  'p_list_utils', ', 'p_const_fast', ', 'p_archive_any', ', 'p_lwp_https', ', 'p_', ', 'p_');

`cd /usb/dist/`
for my $it (@ports)
{
  `cd /usb/dist/$it`;
  `tar -xC /usr/ports/$i -f $i`;
  `.configure`;
  `make`;
  `make install`;
}

# CONFIG OVERWRITE ####################













# ONETIMEONLY ##############
`zfs create zroot/nfs`;
`zfs create zroot/ftp`;

`mkdir /HIVE && chmod 550 /HIVE`;
`mkdir /net && chmod 550 /net`;
`mkdir /pool && chmod 550 /pool/`;
`mkdir /g && chmod 550 /g/`;

`zfs set sharenfs=on zroot/nfs`;
`mkdir /zroot/nfs/pub`;
`mkdir /zroot/nfs/dump`;
`chmod 0777 /zroot/nfs/pub`;
`chmod 0333 /zroot/nfs/dump`;
`chmod 0777 /zroot/ftp/pub`;
`chmod 0333 /zroot/ftp/dump`;
`echo 'console none unknown off insecure' >> /etc/ttys`;
`echo 'crypt_default=blf' >> /etc/auth.conf`;
`sed 'passwd_format="blf"'`;


########################################
# GRAB BY                              #
########################################
# BSD PORTS ###########################
## make fetch from /usr/ports/$pkg_path
## cp /usr/ports/distfiles/$pkg /usb/distfiles 

# PERL MODS ###########################
sub pop_dist
{
  `cd /usb/dist/`
  my @mod = ('LWP::UserAgent', 'File::Find::Rule', 'Digest::SHA', \
    'Parallel::ForkManager', 'File::LibMagic', 'List::Utils', \
    'Const::Fast', 'Archive::Any', 'LWP::Protocol::https', \
    '', '');
  for my $mod (@mod)
    { `cpan -g $mod`; }
}
