#!/usr/local/bin/perl
use Exporter;
package HB::PSKOPIE;
@EXPORT = qw(pskopie);
#
# PSKOPIE #####################################
# Pre Shared Key Onetime Password In Everything

sub pskopie
{
  my ($user) = @_;
# PSK #########################################
  my $key = keygen($user);

  open(my $kfh, '>', '/host');
  print $kfh $key;

  `mkdir /keys`;
  `chmod 550`;
  `chown root`;

  `cp /usb/keys/* /keys/`;

# OPIE ########################################
  `su $user && opieaccess -f && exit`;
  `su $user && opiekeys && exit`;
}
