#!/usr/local/bin/perl
use strict; use warnings;
use Exporter;
package HB::USR;
my @EXPORT = qw(usr);
#
##############################
# USR - unix user group setup

# {{ null }} nologin vpsrsh 
# {{ low }} norm seer
# {{ prime }} heir lord root

# TEST #######################
usr();

sub usr 
{
# seer: ftp mail log_mkrx log_hive 

# norm #######################

  `pw userdel toor`; # remove uucp in favor of scp

  `pw groupadd norm`;
  `pw useradd -n norm -g norm -d /usr/home/norm -s /usr/local/bin/bash`;

  `mkdir /usr/home/norm/`;
  `chmod 550 /usr/home/norm/`;
  `chown norm /usr/home/norm/`;

  `mkdir /usr/home/norm/.ssh/`;
  `chmod -R 500 /usr/home/norm/.ssh/`;
  `chown norm /usr/home/norm/.ssh/`;

  `mkdir /usr/home/norm/bin/`;
  `cp -R /usb/bin /usr/home/bin/`;
  `chmod -R 500 /usr/home/norm/bin/`;
  `chown norm /usr/home/norm/bin/`;

  `mkdir /usr/home/norm/o/`;
  `chmod 700 /usr/home/norm/o/`;
  `chown norm /usr/home/norm/o/`;
 
  `cp /usb/distfiles/.bash_profile /usr/home/norm/.bash_profile`;
  `chmod 500 /usr/home/norm/.bash_profile`;
  `chown norm /usr/home/norm/.bash_profile`;

  `openssl ecparam -name c2tnb431r1 -genkey -out /usr/home/norm/.ssh/id_rsa -param_enc explicit`;
  `openssl ec -in /usr/home/norm/.ssh/id_rsa -pubout -out /usr/home/norm/.ssh/id_rsa.pub -param_enc explicit`;
# seer  #######################
  `pw groupadd seer`;
  `pw useradd -n seer -g seer -d /usr/home/seer -s /usr/local/bin/bash`;

  `mkdir /usr/home/seer/`;
  `chmod 550 /usr/home/seer`;
  `chown seer /usr/home/seer/`;

  `mkdir /usr/home/seer/.ssh`;
  `chmod -R 500 /usr/home/seer/.ssh`;
  `chown seer /usr/home/seer/.ssh`;

  `mkdir /usr/home/seer/bin`;
  `cp -R /usb/bin /usr/home/seer/bin/`;
  `chmod -R 500 /usr/home/seer/bin`;
  `chown seer /usr/home/seer/bin`;

  `mkdir /usr/home/seer/o`;
  `chmod 700 /usr/home/seer/o`;
  `chown seer /usr/home/seer/o`;

  `cp /usb/distfiles/.bash_profile /usr/home/seer/.bash_profile`;
  `chmod 500 /usr/home/seer/.bash_profile`;
  `chown seer /usr/home/seer/.bash_profile`;

  `openssl ecparam -name c2tnb431r1 -genkey -out /usr/home/seer/.ssh/id_rsa -param_enc explicit`;
  `openssl ec -in /usr/home/seer/.ssh/id_rsa -pubout -out /usr/home/seer/.ssh/id_rsa.pub -param_enc explicit`;
# heir  #######################
# OPIE (README)
  `pw groupadd heir`;
  `mkdir /usr/home/heir/`;
  `pw useradd -n heir -g heir -d /usr/home/heir -s /usr/local/bin/bash`;

  `chmod 550 /usr/home/heir`;
  `chown heir /usr/home/heir`;

  `mkdir /usr/home/heir/.ssh`;
  `chmod -R 500 /usr/home/heir/.ssh`;
  `chown heir /usr/home/heir/.ssh`;

  `mkdir /usr/home/heir/bin`;
  `cp -R /usb/bin /usr/home/heir/bin/`;
  `chmod -R 500 /usr/home/heir/bin`;
  `chown heir /usr/home/heir/bin`;

  `mkdir /usr/home/heir/o`;
  `chmod 700 /usr/home/heir/o`;
  `chown heir /usr/home/heir/o`;
 
  `cp /usb/distfiles/.bash_profile /usr/home/heir/.bash_profile`;
  `chmod 500 /usr/home/heir/.bash_profile`;
  `chown heir /usr/home/heir/.bash_profile`;

  `openssl ecparam -name c2tnb431r1 -genkey -out /usr/home/heir/.ssh/id_rsa -param_enc explicit`;
  `openssl ec -in /usr/home/heir/.ssh/id_rsa -pubout -out /usr/home/heir/.ssh/id_rsa.pub -param_enc explicit`;
# lord #######################
# OPIE (README)
  `mkdir /usr/home/lord/`;
  `pw useradd -n lord -g wheel -d /usr/home/lord -s /usr/local/bin/bash`;

  `chmod 550 /usr/home/lord`;
  `chown lord /usr/home/lord/`;

  `mkdir /usr/home/lord/.ssh`;
  `chmod -R 500 /usr/home/lord/.ssh`;
  `chown lord /usr/home/lord/.ssh`;

  `mkdir /usr/home/lord/bin`;
  `chmod -R 500 /usr/home/lord/bin`;
  `chown lord /usr/home/lord/bin`;

  `mkdir /usr/home/lord/o`;
  `chmod 700 /usr/home/lord/o`;
  `chown lord /usr/home/lord/o`;
 
  `cp /usb/distfiles/.bash_profile /usr/home/lord/.bash_profile`;
  `chmod 500 /usr/home/lord/.bash_profile`;
  `chown lord /usr/home/lord/.bash_profile`;
  
  `openssl ecparam -name c2tnb431r1 -genkey -out /usr/home/lord/.ssh/id_rsa -param_enc explicit`;
  `openssl ec -in /usr/home/lord/.ssh/id_rsa -pubout -out /usr/home/lord/.ssh/id_rsa.pub -param_enc explicit`;

  `pw groupmod heir -m lord`;
}
# root #######################
# OPIE (README)
